# Generated by Django 3.2 on 2022-01-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='cuisine',
        ),
    ]
