# Generated by Django 3.2 on 2022-01-25 12:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_restaurant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default', max_length=255, verbose_name='image'),
        ),
    ]
