# Generated by Django 3.2 on 2022-02-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20220125_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
