# Generated by Django 3.2 on 2022-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='county',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
