# Generated by Django 3.2 on 2022-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='county',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
