# Generated by Django 3.2 on 2022-02-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_restaurant_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='author_slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
