# Generated by Django 3.2 on 2022-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_restaurant_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='author_slug',
            field=models.SlugField(max_length=100),
        ),
    ]
