# Generated by Django 3.2 on 2022-02-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_comment_name_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
