# Generated by Django 3.2 on 2022-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_cuisine',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
